theme: jekyll-theme-cayman
title: My knowlege base
description: Мои заметки о программировании, data science и алгоритмах, собранные в процессе обучения
baseurl: "" # the subpath of your site, e.g. /blog

plugins:
  - jekyll-sitemap