theme: jekyll-theme-cayman
title: My knowlege base
description: >- # this means to ignore newlines until "baseurl:"
  Мои заметки о программировании, data science и алгоритмах, собранные в процессе обучения
baseurl: "/myknowlegebase" # the subpath of your site, e.g. /blog
url: "https://konstantinklepikov.github.io" # the base hostname & protocol for your site
owner_url: "https://github.com/KonstantinKlepikov"
owner_name: "KonstantinKlepikov"

exclude: [.vscode, .foam, readme.md, LICENSE]

plugins:
  - jekyll-sitemap
  - jekyll-environment-variables

github: [metadata]

site_tags: 
  - market-stocks
  - cv
  - do
  - docker
  - fastapi
  - git
  - heroku
  - http
  - js
  - sqlalchemy
  - vscode
  - tests
  - templating
  - cl
