title: My knowledge base
description: >- # this means to ignore newlines until "baseurl:"
  Мои заметки о программировании, data science и алгоритмах, собранные в процессе обучения
baseurl: "/myknowlegebase" # the subpath of your site, e.g. /blog
url: "https://konstantinklepikov.github.io" # the base hostname & protocol for your site
owner_url: "https://github.com/KonstantinKlepikov"
owner_name: "KonstantinKlepikov"

exclude:
  - .vscode
  - .foam
  - readme.md
  - LICENSE
  - Gemfile
  - gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - tag_generator.py

social:
  links:
    - https://t.me/KlepikovKonstantin
    - https://github.com/KonstantinKlepikov
lang: ru_RU

# Build settings
markdown: kramdown
theme: jekyll-swiss
theme_color: magenta
plugins:
  - jekyll-sitemap
  - jekyll-environment-variables
  - jekyll-seo-tag

github: [metadata]
