theme: jekyll-theme-cayman
title: My knowlege base
description: >- # this means to ignore newlines until "baseurl:"
  Мои заметки о программировании, data science и алгоритмах, собранные в процессе обучения
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://konstantinklepikov.github.io/myknowlegebase" # the base hostname & protocol for your site

exclude: [.vscode, .foam, readme.md]

plugins:
  - jekyll-sitemap
  - jekyll-feed